// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';

var Lexer$MyCCompiler = require("./Lexer.bs.js");
var Token$MyCCompiler = require("./Token.bs.js");

var program_text = "\n  int   main    (  )  {   return100 ; }";

Token$MyCCompiler.printTokenList(Lexer$MyCCompiler.lex(program_text));

exports.program_text = program_text;
/*  Not a pure module */
