// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';


function printAST(prog) {
  console.log("AST del parser aqui \n");
  return prog;
}

exports.printAST = printAST;
/* No side effect */
