// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';

var Belt_SetInt = require("bs-platform/lib/js/belt_SetInt.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

console.log("asdasdasdas");

console.log("green");

function sum(item) {
  if (item) {
    return (item[0] + sum(item[1]) | 0) + sum(item[2]) | 0;
  } else {
    return 0;
  }
}

var miArbol = /* Node */[
  1,
  /* Node */[
    7,
    /* Node */[
      4,
      /* Leaf */0,
      /* Leaf */0
    ],
    /* Node */[
      6,
      /* Leaf */0,
      /* Leaf */0
    ]
  ],
  /* Node */[
    5,
    /* Node */[
      10,
      /* Leaf */0,
      /* Leaf */0
    ],
    /* Node */[
      60,
      /* Leaf */0,
      /* Leaf */0
    ]
  ]
];

var resultado = sum(miArbol);

console.log(resultado);

var s = String(8);

var result = s + s;

console.log("Result: " + (String(result) + ""));

Belt_SetInt.fromArray(/* array */[
      3,
      5,
      2,
      5,
      4,
      6,
      2
    ]);

var items = /* :: */[
  1,
  /* :: */[
    2,
    /* :: */[
      3,
      /* :: */[
        4,
        /* :: */[
          5,
          /* [] */0
        ]
      ]
    ]
  ]
];

var items2 = /* :: */[
  0,
  items
];

console.log(items2);

throw [
      Caml_builtin_exceptions.match_failure,
      /* tuple */[
        "Demo.re",
        57,
        4
      ]
    ];

/*  Not a pure module */
