// Generated by BUCKLESCRIPT VERSION 4.0.8, PLEASE EDIT WITH CARE
'use strict';


function generate_exp(ast_exp) {
  var decimal = String(ast_exp[0]);
  var return_statement = "    movl    " + (decimal + ", %eax");
  console.log(return_statement);
  return /* () */0;
}

function visit_statement(param) {
  console.log("    ret");
  return /* () */0;
}

function generate_statement(param) {
  generate_exp(/* Const */[2]);
  return visit_statement(/* () */0);
}

function gen_function_code(param) {
  console.log("_main:");
  generate_exp(/* Const */[2]);
  return visit_statement(/* () */0);
}

function generate_code(ast) {
  console.log("    .globl _main");
  return gen_function_code(/* () */0);
}

exports.generate_exp = generate_exp;
exports.visit_statement = visit_statement;
exports.generate_statement = generate_statement;
exports.gen_function_code = gen_function_code;
exports.generate_code = generate_code;
/* No side effect */
