// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Ast$Nqcc = require("./Ast.bs.js");
var Token$Nqcc = require("./Token.bs.js");
var Words$Nqcc = require("./Words.bs.js");
var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function generate_factor(ast, reg) {
  switch (ast.tag | 0) {
    case 0 : 
        var factor = ast[1];
        var ope = ast[0];
        if (Token$Nqcc.identificador(ope) === "LogNeg") {
          var return_unop = "    cmpl   $0, " + (Words$Nqcc.registro(reg) + ("\n    movl   $0, " + (Words$Nqcc.registro(1) + "\n    sete   %al ")));
          generate_factor(factor, 0);
          console.log(return_unop);
          return /* () */0;
        } else {
          var return_unop$1 = "    " + (Words$Nqcc.tradu(Token$Nqcc.identificador(ope)) + ("    " + Words$Nqcc.registro(1)));
          generate_factor(factor, 0);
          console.log(return_unop$1);
          return /* () */0;
        }
    case 1 : 
        throw [
              Caml_builtin_exceptions.match_failure,
              /* tuple */[
                "Generator.re",
                2,
                2
              ]
            ];
    case 2 : 
        var decimal = String(ast[0]);
        var return_statement = "    movl    " + (decimal + (", " + Words$Nqcc.registro(reg)));
        console.log(return_statement);
        return /* () */0;
    
  }
}

function generate_termino(ast) {
  switch (ast.tag | 0) {
    case 0 : 
        return generate_factor(ast[0], 0);
    case 1 : 
        throw [
              Caml_builtin_exceptions.match_failure,
              /* tuple */[
                "Generator.re",
                20,
                2
              ]
            ];
    case 2 : 
        generate_factor(ast[1], 0);
        generate_factor(ast[2], 1);
        var return_termino = "    " + (Words$Nqcc.tradu(Token$Nqcc.identificador(ast[0])) + ("    " + Words$Nqcc.registro(1)));
        console.log(return_termino);
        return /* () */0;
    
  }
}

function generate_exp(ast_exp) {
  switch (ast_exp.tag | 0) {
    case 0 : 
        return generate_termino(ast_exp[0]);
    case 1 : 
        throw [
              Caml_builtin_exceptions.match_failure,
              /* tuple */[
                "Generator.re",
                31,
                2
              ]
            ];
    case 2 : 
        var ope = ast_exp[0];
        generate_termino(ast_exp[1]);
        generate_termino(ast_exp[2]);
        if (Token$Nqcc.identificador(ope) === "Negation") {
          var return_unop = "    " + (Words$Nqcc.tradu(Token$Nqcc.identificador(ope)) + ("    " + Words$Nqcc.registro(1)));
          console.log(return_unop);
        }
        var return_exp = "    add    " + (Words$Nqcc.registro(0) + (", " + Words$Nqcc.registro(1)));
        console.log(return_exp);
        return /* () */0;
    
  }
}

function visit_statement(name) {
  var return_statement = "    " + Words$Nqcc.tradu(name);
  console.log(return_statement);
  return /* () */0;
}

function generate_statement(ast) {
  if (Ast$Nqcc.identi_statement(ast) === true) {
    var name_state = Ast$Nqcc.ext_name_statement(ast);
    var node_exp = Ast$Nqcc.ext_statement(ast);
    generate_exp(node_exp);
    return visit_statement(name_state);
  } else {
    return 0;
  }
}

function gen_function_code(ast) {
  if (Ast$Nqcc.identi_fun_decl(ast) === true) {
    var functionName = Ast$Nqcc.ext_name_fun_decl(ast);
    var node_statement = Ast$Nqcc.ext_fun_decl(ast);
    console.log("_" + (functionName + ":"));
    return generate_statement(node_statement);
  } else {
    return 0;
  }
}

function generate_code(ast) {
  if (Ast$Nqcc.identi_prog(ast) === true) {
    var node_prog = Ast$Nqcc.ext_prog(ast);
    console.log("    .globl _main");
    return gen_function_code(node_prog);
  } else {
    console.log(Ast$Nqcc.ext_prog_err(ast));
    return /* () */0;
  }
}

exports.generate_factor = generate_factor;
exports.generate_termino = generate_termino;
exports.generate_exp = generate_exp;
exports.visit_statement = visit_statement;
exports.generate_statement = generate_statement;
exports.gen_function_code = gen_function_code;
exports.generate_code = generate_code;
/* No side effect */
