// Generated by BUCKLESCRIPT VERSION 4.0.14, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function tradu(t) {
  switch (t) {
    case "Addition" : 
        return "add";
    case "Bitwise" : 
        return "not";
    case "Division" : 
        return "div";
    case "Multiplication" : 
        return "mul";
    case "Negation" : 
        return "neg";
    case "ReturnKeyword" : 
        return "ret";
    default:
      throw [
            Caml_builtin_exceptions.match_failure,
            /* tuple */[
              "Words.re",
              1,
              26
            ]
          ];
  }
}

function registro(n) {
  switch (n) {
    case 0 : 
        return "%eax";
    case 1 : 
        return "%ebx";
    case 2 : 
        return "%ecx";
    case 3 : 
        return "%edx";
    default:
      throw [
            Caml_builtin_exceptions.match_failure,
            /* tuple */[
              "Words.re",
              12,
              27
            ]
          ];
  }
}

exports.tradu = tradu;
exports.registro = registro;
/* No side effect */
