// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Caml_builtin_exceptions = require("bs-platform/lib/js/caml_builtin_exceptions.js");

function parse_constant() {
  return /* Const */[2];
}

function parse_statement() {
  return /* Return */[/* Const */[2]];
}

function parse_function(tokenList) {
  if (tokenList) {
    var $$return = parse_statement(tokenList);
    return /* Fun */[
            "main",
            $$return
          ];
  } else {
    throw [
          Caml_builtin_exceptions.match_failure,
          /* tuple */[
            "Parser.re",
            9,
            6
          ]
        ];
  }
}

function parse_program(tokenList) {
  var func_decl = parse_function(tokenList);
  return /* Prog */[func_decl];
}

exports.parse_constant = parse_constant;
exports.parse_statement = parse_statement;
exports.parse_function = parse_function;
exports.parse_program = parse_program;
/* No side effect */
