// Generated by BUCKLESCRIPT VERSION 4.0.6, PLEASE EDIT WITH CARE
'use strict';

var Belt_List = require("bs-platform/lib/js/belt_List.js");

function tokenToString(acummulator, t) {
  var result;
  if (typeof t === "number") {
    switch (t) {
      case 0 : 
          result = "OpenBrance";
          break;
      case 1 : 
          result = "CloseBrace";
          break;
      case 2 : 
          result = "OpenParen";
          break;
      case 3 : 
          result = "CloseParen";
          break;
      case 4 : 
          result = "Semicolon";
          break;
      case 5 : 
          result = "ReturnKeyword";
          break;
      case 6 : 
          result = "Invalid Token";
          break;
      
    }
  } else {
    result = t.tag ? "(Constant: " + (String(t[0]) + ")") : "(Id: " + (t[0] + ")");
  }
  return acummulator + (" " + (result + ","));
}

function tokenListToString(tokensList) {
  var comma_regexp = (/,$/);
  var stringList = Belt_List.reduce(tokensList, "[", tokenToString);
  return stringList.replace(comma_regexp, " ]");
}

function printTokenList(tokenList) {
  console.log(tokenListToString(tokenList));
  return tokenList;
}

exports.tokenToString = tokenToString;
exports.tokenListToString = tokenListToString;
exports.printTokenList = printTokenList;
/* No side effect */
